services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://yash:yash@cluster0.mongodb.net/?retryWrites=true&w=majority"
